"use client";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ItemCountProvider } from "@/itemCountContext";
import { ClerkProvider, ClerkLoaded, ClerkLoading } from "@clerk/nextjs";
import Navbar from "./utils/Navbar";

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

// I took out export because you can't have export & "use client" in the same file
// I needed "use client" in order to use the ItemCountProvider
// I added the provider here so that all routes have access to the context

// IMPORTANT: look into how to get the metadata back later if I have time....
const metadata: Metadata = {
	title: "E-commerce Site",
	description: "Generated by Leul Mesfin",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ClerkProvider>
			<html lang="en">
				<body
					className={`${geistSans.variable} ${geistMono.variable} antialiased`}
				>
					<ClerkLoading>
						<div className="fixed top-0 left-0 w-screen h-screen bg-white flex justify-center items-center">
							<p className="text-2xl font-bold text-gray-800">Loading...</p>
						</div>
					</ClerkLoading>

					<ClerkLoaded>
						<Navbar />
						<ItemCountProvider>{children}</ItemCountProvider>
					</ClerkLoaded>
				</body>
			</html>
		</ClerkProvider>
	);
}
