"use client";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ItemCountProvider } from "@/itemCountContext";

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

// I took out export because you can't have export & "use client" in the same file
// I needed "use client" in order to use the ItemCountProvider
// I added the provider here so that all routes have access to the context

// IMPORTANT: look into how to get the metadata back later if I have time....
const metadata: Metadata = {
	title: "E-commerce Site",
	description: "Generated by Leul Mesfin",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<ItemCountProvider>{children}</ItemCountProvider>
			</body>
		</html>
	);
}
